import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import { writeFile, mkdir } from 'node:fs/promises';
const browser = await chromium.launch({headless:true});
const report = { browser: await browser.version(), results: [] };
await mkdir('evidence', {recursive:true});
try {
for (const width of [1440,390]) {
 const context = await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'});
 const page = await context.newPage();
 const errors = [], external = [];
 page.on('pageerror',e => errors.push(e.message));
 page.on('request',r => {if (!r.url().startsWith('http://localhost:4173')) external.push(r.url());});
 await page.goto('http://localhost:4173', {waitUntil:'networkidle'});
 await page.evaluate(() => document.fonts.ready);
 assert.equal(await page.locator('h1').count(),1);
 assert.equal(await page.locator('meta[name=robots]').getAttribute('content'),'noindex,nofollow');
 assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
 const missingAnchors = await page.locator('a[href^="#"]').evaluateAll(links => links.filter(a => !document.querySelector(a.getAttribute('href'))).map(a=>a.href));
 assert.deepEqual(missingAnchors,[]);
 await page.keyboard.press('Tab');
 assert.equal(await page.locator('.skip').evaluate(el => el === document.activeElement),true);
 const focusOutline = await page.locator('.skip').evaluate(el=>getComputedStyle(el).outlineStyle);
 assert.notEqual(focusOutline,'none');
 await page.locator('.hero .button').click();
 await page.waitForURL('**/#demo');
 const original = await page.locator('#proposal-text').inputValue();
 await page.locator('#proposal-text').fill('Une reformulation locale de démonstration.');
 await page.getByRole('tab',{name:'LinkedIn',exact:true}).click();
 assert.notEqual(await page.locator('#proposal-text').inputValue(),original);
 await page.getByRole('tab',{name:'Facebook',exact:true}).click();
 assert.equal(await page.locator('#proposal-text').inputValue(),'Une reformulation locale de démonstration.');
 await page.locator('#approve').click();
 assert.match(await page.locator('#feedback').innerText(),/validée dans la démo/);
 await page.locator('#restore').click();
 assert.equal(await page.locator('#proposal-text').inputValue(),original);
 await page.locator('#proposal-text').fill('  ');
 assert.equal(await page.locator('#approve').isDisabled(),true);
 await page.locator('#restore').click();
 await page.getByRole('tab',{name:'Facebook',exact:true}).focus();
 await page.keyboard.press('ArrowRight');
 assert.equal(await page.getByRole('tab',{name:'Instagram',exact:true}).getAttribute('aria-selected'),'true');
 await page.locator('#image-available').uncheck();
 assert.equal(await page.locator('#approve').isDisabled(),true);
 assert.match(await page.locator('#availability').innerText(),/Diffusion bloquée/);
 await page.locator('#image-available').check();
 assert.equal(await page.locator('#approve').isDisabled(),false);
 await page.locator('#article-select').selectOption('night');
 assert.match(await page.locator('#article-title').innerText(),/vélo/);
 await page.getByRole('tab',{name:'X',exact:true}).click();
 assert.match(await page.locator('#proposal-text').inputValue(),/éclairage/);
 await page.locator('#approve').click();
 await page.locator('#demo').screenshot({path:`evidence/demo-${width}.png`});
 const summary = page.locator('summary').first();
 await summary.focus(); await page.keyboard.press('Enter');
 assert.equal(await page.locator('details').first().getAttribute('open'),'');
 const a11y = await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();
 await page.reload({waitUntil:'networkidle'});
 assert.equal(await page.locator('#proposal-text').inputValue(),original);
 assert.equal(await page.evaluate(()=>localStorage.length + sessionStorage.length),0);
 assert.equal((await context.cookies()).length,0);
 await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:`evidence/${width===1440?'desktop':'mobile'}.png`,fullPage:true});
 const geometry = await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,fonts:document.fonts.check('16px "Bricolage Grotesque Variable"')}));
 report.results.push({width,geometry,focusOutline,errors,externalRequests:external,a11yViolations:a11y.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)})),interactions:'CTA, liens, clavier, onglets, modification, validation, restauration, vide, image Instagram, article, FAQ, réinitialisation : OK'});
 await context.close();
}
await writeFile('evidence/report.json',JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
assert(report.results.every(r=>r.errors.length===0 && r.externalRequests.length===0 && r.a11yViolations.length===0));
} finally {await browser.close();}
